name: 'promote-Nexus-repository-to-MavenCentral'
description: 'Provide a description here'
author: "Vilius Sutkus '89"
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
